version: 2.1

description: Workflow de build, test, linting, conteneurisation et déploiement.

display:
  source_url: https://github.com/chrisopenclass/Python-OC-Lettings-FR-master

orbs:
  python: circleci/python@0.3.2
  docker: circleci/docker@2.0.1
  heroku: circleci/heroku@1.2.6

executors:
  docker-publisher:
    environment:
      image_name: lapinator1593/oc-learning
    docker: 
      - image: cimg/python:3.10.5
        auth:
          username: user
          password: password

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: python -m pytest

  lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: python -m flake8

  docker-publish:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: publish to dockerhub
          command: |
            echo password | docker login -u user --password-stdin
            docker build -t ${image_name} .
            docker image push test:latest
      - filters:
          branches:
          only: main

  deploy:
    executor: heroku/default
    steps:
      - checkout
      # Install Heroku if not already installed
      - heroku/install
      # Deploy app to Heroku
      - heroku/deploy-via-git:
          app-name: APP_NAME
          api-key: API_KEY

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - docker/publish:
          docker-username: user
          docker-password: password
          image: image_name
          requires:
            - build
            - test
            - lint
      - deploy:
          requires:
            - docker/publish
          filters:
            branches:
              only: main