version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

workflows:
  deploy:
    jobs:
      - build_and_test
      - build_push_docker_hub:
          requires:
            - build_and_test
     
      - heroku/deploy-via-git:
          requires:
            - build_and_test
            - build_push_docker_hub   
          filters:
           branches:
             only: master
          pre-steps:
            - heroku/install
            - run:
                command: |
                  heroku config:set SENTRY_URL=$SENTRY_URL -a oc-lettings-oc
                  heroku config:set SECRET_KEY=$SECRET_KEY -a oc-lettings-oc
                  heroku config:set DATABASE_URL=$DATABASE_URL -a oc-lettings-oc
                  heroku config:set SQLITE_URL=$SQLITE_URL -a oc-lettings-oc
              
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install Django and dependencies
          command: |
           pip install -r requirements.txt
      - run:
          name: Run tests and linting
          command: |
            pytest
            flake8
  build_push_docker_hub:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/oc-lettings
          extra_build_args: "-t $DOCKER_LOGIN/oc-lettings"
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $DOCKER_LOGIN/oc-lettings
          tag: "latest"
      - docker/push:
          image: $DOCKER_LOGIN/oc-lettings
          tag: $CIRCLE_SHA1