version: 2.1

description: Workflow de build, test, linting, conteneurisation et déploiement.

display:
  source_url: https://github.com/chrisopenclass/Python-OC-Lettings-FR-master

orbs:
  python: circleci/python@0.3.2
  docker: circleci/docker@2.0.1
  heroku: circleci/heroku@1.2.6

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: lapinator1593/oc-learning
    docker: 
      - image: cimg/python:3.10.5
        auth:
          username: user
          password: password

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: python -m pytest

  lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: python -m flake8

  docker-publish:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: publish to dockerhub
          command: |
            echo password | docker login -u user --password-stdin
            docker push $IMAGE_NAME:latest
      - filters:
          branches:
          only: main

  deploy:
    machine: True
    steps:
      - checkout
      - run:
          name: Install Heroku 
          command: |
            set -e
            sudo curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Pulling container from Dockerhub
          command: |
            docker login -u $user -p $password
            docker pull $IMAGE_NAME:$CIRCLE_SHA1
      
      - run:
          name: Pushing container to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 registry.heroku.com/$APP_NAME/web
            docker push registry.heroku.com/$APP_NAME/web
      
      - run:
          name: Releasing container
          command: |          
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web -a $APP_NAME


workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - test
      - docker/publish:
          docker-username: user
          docker-password: password
          image: $IMAGE_NAME
          requires:
            - lint
      - deploy:
          requires:
            - docker/publish
          filters:
            branches:
              only: main