# Generated by Django 3.0 on 2022-06-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name': 'adress', 'verbose_name_plural': ' addresses'},
        ),
    ]
