# Generated by Django 3.0 on 2022-06-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20220620_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name_plural': ' Addresses'},
        ),
    ]
