# Generated by Django 3.0 on 2022-06-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20220620_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': ' Addresses'},
        ),
    ]
