# Generated by Django 3.0 on 2022-06-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0005_auto_20220620_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letting',
            options={},
        ),
    ]
